import { MovieDetail } from '../../src/models/movieDetail'

export const movieDetailMock: MovieDetail = {
  "adult": false,
  "backdrop_path": "/4zlOPT9CrtIX05bBIkYxNZsm5zN.jpg",
  "belongs_to_collection": {
      "id": 1370345,
      "name": "The Wild Robot Collection",
      "poster_path": "",
      "backdrop_path": ""
  },
  "budget": 78000000,
  "genres": [
      {
          "id": 16,
          "name": "Animation"
      },
      {
          "id": 878,
          "name": "Science Fiction"
      },
      {
          "id": 10751,
          "name": "Family"
      }
  ],
  "homepage": "https://www.thewildrobotmovie.com",
  "id": 1184918,
  "imdb_id": "tt29623480",
  "origin_country": [
      "US"
  ],
  "original_language": "en",
  "original_title": "The Wild Robot",
  "overview": "After a shipwreck, an intelligent robot called Roz is stranded on an uninhabited island. To survive the harsh environment, Roz bonds with the island's animals and cares for an orphaned baby goose.",
  "popularity": 1822.697,
  "poster_path": "/wTnV3PCVW5O92JMrFvvrRcV39RU.jpg",
  "production_companies": [
      {
          "id": 521,
          "logo_path": "/3BPX5VGBov8SDqTV7wC1L1xShAS.png",
          "name": "DreamWorks Animation",
          "origin_country": "US"
      }
  ],
  "production_countries": [
      {
          "iso_3166_1": "US",
          "name": "United States of America"
      }
  ],
  "release_date": "2024-09-12",
  "revenue": 111406047,
  "runtime": 102,
  "spoken_languages": [
      {
          "english_name": "English",
          "iso_639_1": "en",
          "name": "English"
      }
  ],
  "status": "Released",
  "tagline": "Discover your true nature.",
  "title": "The Wild Robot",
  "video": false,
  "vote_average": 8.1,
  "vote_count": 192,
  "credits": {
      "cast": [
          {
              "adult": false,
              "gender": 1,
              "id": 1267329,
              "known_for_department": "Acting",
              "name": "Lupita Nyong'o",
              "original_name": "Lupita Nyong'o",
              "popularity": 34.404,
              "profile_path": "/y40Wu1T742kynOqtwXASc5Qgm49.jpg",
              "cast_id": 9,
              "character": "Roz (voice)",
              "credit_id": "65c03d8ffc65380163eaf41c",
              "order": 0
          },
          {
              "adult": false,
              "gender": 2,
              "id": 1253360,
              "known_for_department": "Acting",
              "name": "Pedro Pascal",
              "original_name": "Pedro Pascal",
              "popularity": 58.405,
              "profile_path": "/9VYK7oxcqhjd5LAH6ZFJ3XzOlID.jpg",
              "cast_id": 10,
              "character": "Fink (voice)",
              "credit_id": "65c03d9f907f260187726bec",
              "order": 1
          },
          {
              "adult": false,
              "gender": 2,
              "id": 1538851,
              "known_for_department": "Acting",
              "name": "Kit Connor",
              "original_name": "Kit Connor",
              "popularity": 29.999,
              "profile_path": "/gCIdbnV9D3lzTaOB0YtuKDz6Nt0.jpg",
              "cast_id": 13,
              "character": "Brightbill (voice)",
              "credit_id": "65c03dbe12c604017c035ecd",
              "order": 2
          },
          {
              "adult": false,
              "gender": 2,
              "id": 2440,
              "known_for_department": "Acting",
              "name": "Bill Nighy",
              "original_name": "Bill Nighy",
              "popularity": 30.812,
              "profile_path": "/ixFI2YCGNGJfwlpI8iyhvVZRg8C.jpg",
              "cast_id": 11,
              "character": "Longneck (voice)",
              "credit_id": "65c03da9b339030165980cd2",
              "order": 3
          },
          {
              "adult": false,
              "gender": 1,
              "id": 1381186,
              "known_for_department": "Acting",
              "name": "Stephanie Hsu",
              "original_name": "Stephanie Hsu",
              "popularity": 8.367,
              "profile_path": "/8gb3lfIHKQAGOQyeC4ynQPsCiHr.jpg",
              "cast_id": 14,
              "character": "Vontra (voice)",
              "credit_id": "65c03dc643999b0184c8effd",
              "order": 4
          },
          {
              "adult": false,
              "gender": 2,
              "id": 2,
              "known_for_department": "Acting",
              "name": "Mark Hamill",
              "original_name": "Mark Hamill",
              "popularity": 16.368,
              "profile_path": "/2ZulC2Ccq1yv3pemusks6Zlfy2s.jpg",
              "cast_id": 15,
              "character": "Thorn (voice)",
              "credit_id": "65e7462dcede690185bf000c",
              "order": 5
          },
          {
              "adult": false,
              "gender": 1,
              "id": 11514,
              "known_for_department": "Acting",
              "name": "Catherine O'Hara",
              "original_name": "Catherine O'Hara",
              "popularity": 32.568,
              "profile_path": "/cMBxHeztNVc8YXKcj084Mdd3f3U.jpg",
              "cast_id": 12,
              "character": "Pinktail (voice)",
              "credit_id": "65c03db1ba480200c968ce60",
              "order": 6
          },
          {
              "adult": false,
              "gender": 2,
              "id": 10182,
              "known_for_department": "Acting",
              "name": "Ving Rhames",
              "original_name": "Ving Rhames",
              "popularity": 26.781,
              "profile_path": "/4gpLVNKPZlVucc4fT2fSZ7DksTK.jpg",
              "cast_id": 17,
              "character": "Thunderbolt (voice)",
              "credit_id": "65e750a31db65d0187944ce9",
              "order": 7
          },
          {
              "adult": false,
              "gender": 2,
              "id": 1488236,
              "known_for_department": "Acting",
              "name": "Matt Berry",
              "original_name": "Matt Berry",
              "popularity": 12.972,
              "profile_path": "/7a1sWg1W7ZmNF8bLSnyAlJgQQGD.jpg",
              "cast_id": 16,
              "character": "Paddler (voice)",
              "credit_id": "65e75097f8595801489a50dc",
              "order": 8
          },
          {
              "adult": false,
              "gender": 0,
              "id": 4967567,
              "known_for_department": "Acting",
              "name": "Boone Storm",
              "original_name": "Boone Storm",
              "popularity": 0.098,
              "profile_path": null,
              "cast_id": 28,
              "character": "Baby Brightbill (voice)",
              "credit_id": "66f749d71a9c9188fecbed15",
              "order": 9
          },
          {
              "adult": false,
              "gender": 0,
              "id": 3745698,
              "known_for_department": "Acting",
              "name": "Alexandra Novelle",
              "original_name": "Alexandra Novelle",
              "popularity": 0.773,
              "profile_path": null,
              "cast_id": 29,
              "character": "Snowdown (voice)",
              "credit_id": "66f749fb2c4bdc9db05f0a1f",
              "order": 10
          },
          {
              "adult": false,
              "gender": 2,
              "id": 1368512,
              "known_for_department": "Acting",
              "name": "Raphael Alejandro",
              "original_name": "Raphael Alejandro",
              "popularity": 14.011,
              "profile_path": "/7wPajmopoSh8RYIVSVemQrUBCJv.jpg",
              "cast_id": 30,
              "character": "Peck (voice)",
              "credit_id": "66f74a072c4bdc9db05f0a28",
              "order": 11
          },
          {
              "adult": false,
              "gender": 2,
              "id": 1975196,
              "known_for_department": "Acting",
              "name": "Paul-Mikél Williams",
              "original_name": "Paul-Mikél Williams",
              "popularity": 1.939,
              "profile_path": "/5f6YOmEZkAzt95Hm2oihuvRCdRK.jpg",
              "cast_id": 31,
              "character": "Feather (voice)",
              "credit_id": "66f74a15f5d56e9ed8a1e579",
              "order": 12
          },
          {
              "adult": false,
              "gender": 2,
              "id": 3745667,
              "known_for_department": "Acting",
              "name": "Eddie Park",
              "original_name": "Eddie Park",
              "popularity": 0.351,
              "profile_path": "/r96gdQnmER5O4RfdBdMOT2sVT5I.jpg",
              "cast_id": 32,
              "character": "Honkington (voice)",
              "credit_id": "66f74a35393cda1d1dcbef45",
              "order": 13
          },
          {
              "adult": false,
              "gender": 2,
              "id": 23680,
              "known_for_department": "Acting",
              "name": "Dee Bradley Baker",
              "original_name": "Dee Bradley Baker",
              "popularity": 14.66,
              "profile_path": "/9oFnToDZWp0I484s7Ua1EzNQQ2m.jpg",
              "cast_id": 33,
              "character": "Raccoons / Squirrels / Badgers (voice)",
              "credit_id": "66f74a42f5d56e9ed8a1e591",
              "order": 14
          },
          {
              "adult": false,
              "gender": 2,
              "id": 42267,
              "known_for_department": "Sound",
              "name": "Randy Thom",
              "original_name": "Randy Thom",
              "popularity": 2.425,
              "profile_path": "/oWv5U4r7NcIlQjs0IxMWE3dsx2l.jpg",
              "cast_id": 34,
              "character": "RECOs (voice)",
              "credit_id": "66f74a4f140fbf6a1a5f096f",
              "order": 15
          },
          {
              "adult": false,
              "gender": 1,
              "id": 112330,
              "known_for_department": "Acting",
              "name": "Avrielle Corti",
              "original_name": "Avrielle Corti",
              "popularity": 1.054,
              "profile_path": "/rgzPmGIVWyufBgMqApTxtHjYZmv.jpg",
              "cast_id": 35,
              "character": "Automated Alarms (voice)",
              "credit_id": "66f74a5fe7d24ebb2ba1e557",
              "order": 16
          },
          {
              "adult": false,
              "gender": 2,
              "id": 1152021,
              "known_for_department": "Acting",
              "name": "Keston John",
              "original_name": "Keston John",
              "popularity": 1.596,
              "profile_path": "/zEqkvuCDDgiErHg3XNyoG5TulUg.jpg",
              "cast_id": 36,
              "character": "Weasel 1 (voice)",
              "credit_id": "66f74a6d393cda1d1dcbef5e",
              "order": 17
          },
          {
              "adult": false,
              "gender": 2,
              "id": 1379386,
              "known_for_department": "Acting",
              "name": "Max Mittelman",
              "original_name": "Max Mittelman",
              "popularity": 10.109,
              "profile_path": "/zQqiIgestpxssPrUXQXkY2Sq0y8.jpg",
              "cast_id": 37,
              "character": "Weasel 2 (voice)",
              "credit_id": "66f74a78140fbf6a1a5f0981",
              "order": 18
          },
          {
              "adult": false,
              "gender": 2,
              "id": 1449707,
              "known_for_department": "Acting",
              "name": "Piotr Michael",
              "original_name": "Piotr Michael",
              "popularity": 4.239,
              "profile_path": "/r9ddS7WpHoLLb0KMEeRE3QSECnW.jpg",
              "cast_id": 38,
              "character": "Broadfoot / Weasel 3 (voice)",
              "credit_id": "66f74a83140fbf6a1a5f098d",
              "order": 19
          },
          {
              "adult": false,
              "gender": 0,
              "id": 4967576,
              "known_for_department": "Acting",
              "name": "Alessandro Beghi",
              "original_name": "Alessandro Beghi",
              "popularity": 0.01,
              "profile_path": null,
              "cast_id": 39,
              "character": "Baby Opossum 1 (voice)",
              "credit_id": "66f74a90393cda1d1dcbef7a",
              "order": 20
          },
          {
              "adult": false,
              "gender": 0,
              "id": 4967578,
              "known_for_department": "Acting",
              "name": "Tiago Martinez",
              "original_name": "Tiago Martinez",
              "popularity": 0.01,
              "profile_path": null,
              "cast_id": 40,
              "character": "Baby Opossum 2 (voice)",
              "credit_id": "66f74aa4e7d24ebb2ba1e576",
              "order": 21
          },
          {
              "adult": false,
              "gender": 0,
              "id": 4967579,
              "known_for_department": "Acting",
              "name": "Becca Last",
              "original_name": "Becca Last",
              "popularity": 0.286,
              "profile_path": null,
              "cast_id": 41,
              "character": "Baby Opossum 3 (voice)",
              "credit_id": "66f74aaf0a12215631cbeea1",
              "order": 22
          },
          {
              "adult": false,
              "gender": 0,
              "id": 4967581,
              "known_for_department": "Acting",
              "name": "Madelyn Turpin",
              "original_name": "Madelyn Turpin",
              "popularity": 0.122,
              "profile_path": null,
              "cast_id": 42,
              "character": "Baby Opossum 3, 5, 6 (voice)",
              "credit_id": "66f74ae3140fbf6a1a5f09b5",
              "order": 23
          },
          {
              "adult": false,
              "gender": 0,
              "id": 4663825,
              "known_for_department": "Acting",
              "name": "Kayleigh Rayne",
              "original_name": "Kayleigh Rayne",
              "popularity": 0.023,
              "profile_path": null,
              "cast_id": 43,
              "character": "Baby Opossum 4, 7 / Baby Bunny 2 / Baby Skunk (voice)",
              "credit_id": "66f74af3f5d56e9ed8a1e5c0",
              "order": 24
          },
          {
              "adult": false,
              "gender": 0,
              "id": 4967583,
              "known_for_department": "Acting",
              "name": "Isabelle Tupin",
              "original_name": "Isabelle Tupin",
              "popularity": 0.056,
              "profile_path": null,
              "cast_id": 44,
              "character": "Baby Opossum 8, 9 / Baby Bunny 1 (voice)",
              "credit_id": "66f74b040f6fa2cfce5f0911",
              "order": 25
          },
          {
              "adult": false,
              "gender": 0,
              "id": 4967584,
              "known_for_department": "Acting",
              "name": "Beckett Blomberg",
              "original_name": "Beckett Blomberg",
              "popularity": 0.043,
              "profile_path": null,
              "cast_id": 45,
              "character": "Baby Opossum 10 / Chipmunk / Baby Lynx (voice)",
              "credit_id": "66f74b100a12215631cbeef3",
              "order": 26
          },
          {
              "adult": false,
              "gender": 0,
              "id": 4967585,
              "known_for_department": "Acting",
              "name": "Damon Fung",
              "original_name": "Damon Fung",
              "popularity": 0.368,
              "profile_path": null,
              "cast_id": 46,
              "character": "Baby Opossum 11 / Baby Otter (voice)",
              "credit_id": "66f74b23393cda1d1dcbef93",
              "order": 27
          },
          {
              "adult": false,
              "gender": 0,
              "id": 4871610,
              "known_for_department": "Acting",
              "name": "King Moore",
              "original_name": "King Moore",
              "popularity": 0.001,
              "profile_path": null,
              "cast_id": 47,
              "character": "Baby Opossum 12 (voice)",
              "credit_id": "66f74b37f5d56e9ed8a1e5f4",
              "order": 28
          },
          {
              "adult": false,
              "gender": 0,
              "id": 3200942,
              "known_for_department": "Editing",
              "name": "Collin Erker",
              "original_name": "Collin Erker",
              "popularity": 0.209,
              "profile_path": null,
              "cast_id": 48,
              "character": "Skunk (voice)",
              "credit_id": "66f74b440a12215631cbeefe",
              "order": 29
          }
      ],
      "crew": [
          {
              "adult": false,
              "gender": 2,
              "id": 69797,
              "known_for_department": "Directing",
              "name": "Dean DeBlois",
              "original_name": "Dean DeBlois",
              "popularity": 6.332,
              "profile_path": "/miMZ0l4rY81NiyMviWz1BeTGtuE.jpg",
              "credit_id": "6515fda7a199a600c49cbdf7",
              "department": "Production",
              "job": "Executive Producer"
          },
          {
              "adult": false,
              "gender": 2,
              "id": 66193,
              "known_for_department": "Directing",
              "name": "Chris Sanders",
              "original_name": "Chris Sanders",
              "popularity": 15.346,
              "profile_path": "/6CtrIOCxggJ5eIAWeFQqd4Hs9FP.jpg",
              "credit_id": "6515fd960499f200e1c69a22",
              "department": "Directing",
              "job": "Director"
          },
          {
              "adult": false,
              "gender": 2,
              "id": 66193,
              "known_for_department": "Directing",
              "name": "Chris Sanders",
              "original_name": "Chris Sanders",
              "popularity": 15.346,
              "profile_path": "/6CtrIOCxggJ5eIAWeFQqd4Hs9FP.jpg",
              "credit_id": "6515fd9993bd6900e12ca342",
              "department": "Writing",
              "job": "Screenplay"
          },
          {
              "adult": false,
              "gender": 2,
              "id": 1847451,
              "known_for_department": "Production",
              "name": "Jeff Hermann",
              "original_name": "Jeff Hermann",
              "popularity": 1.529,
              "profile_path": null,
              "credit_id": "6515fda00499f200c44ef601",
              "department": "Production",
              "job": "Producer"
          },
          {
              "adult": false,
              "gender": 2,
              "id": 1681250,
              "known_for_department": "Art",
              "name": "Raymond Zibach",
              "original_name": "Raymond Zibach",
              "popularity": 0.64,
              "profile_path": null,
              "credit_id": "6515feb4d4653709df433b0c",
              "department": "Art",
              "job": "Production Design"
          },
          {
              "adult": false,
              "gender": 1,
              "id": 2001828,
              "known_for_department": "Editing",
              "name": "Mary Blee",
              "original_name": "Mary Blee",
              "popularity": 1.736,
              "profile_path": null,
              "credit_id": "6515fec093bd690138fc7bb3",
              "department": "Editing",
              "job": "Editor"
          },
          {
              "adult": false,
              "gender": 1,
              "id": 1806628,
              "known_for_department": "Art",
              "name": "Heidi Jo Gilbert",
              "original_name": "Heidi Jo Gilbert",
              "popularity": 0.706,
              "profile_path": null,
              "credit_id": "6515feba93bd690138fc7bad",
              "department": "Writing",
              "job": "Head of Story"
          },
          {
              "adult": false,
              "gender": 2,
              "id": 4296354,
              "known_for_department": "Writing",
              "name": "Peter Brown",
              "original_name": "Peter Brown",
              "popularity": 1.057,
              "profile_path": "/9utvGyOHFGVEmTo6VT7846bK8WJ.jpg",
              "credit_id": "65e76f00229ae20185569ad7",
              "department": "Writing",
              "job": "Novel"
          },
          {
              "adult": false,
              "gender": 2,
              "id": 7764,
              "known_for_department": "Sound",
              "name": "Richard Hymns",
              "original_name": "Richard Hymns",
              "popularity": 1.35,
              "profile_path": "/970GjgH2nfqsnEsimqLvLYoYTQn.jpg",
              "credit_id": "65e7841542f19f01878c550b",
              "department": "Sound",
              "job": "Supervising Sound Editor"
          },
          {
              "adult": false,
              "gender": 2,
              "id": 2216,
              "known_for_department": "Sound",
              "name": "Gary Rydstrom",
              "original_name": "Gary Rydstrom",
              "popularity": 2.558,
              "profile_path": "/1DoKaxoJlz6hV9bai43e07GxGQf.jpg",
              "credit_id": "65e78456c15f8901861571fa",
              "department": "Sound",
              "job": "Sound Re-Recording Mixer"
          },
          {
              "adult": false,
              "gender": 2,
              "id": 2216,
              "known_for_department": "Sound",
              "name": "Gary Rydstrom",
              "original_name": "Gary Rydstrom",
              "popularity": 2.558,
              "profile_path": "/1DoKaxoJlz6hV9bai43e07GxGQf.jpg",
              "credit_id": "65e78436caab6d018594edb0",
              "department": "Sound",
              "job": "Sound Designer"
          },
          {
              "adult": false,
              "gender": 2,
              "id": 1400906,
              "known_for_department": "Sound",
              "name": "Chris Scarabosio",
              "original_name": "Chris Scarabosio",
              "popularity": 2.031,
              "profile_path": "/2kPNj5f6ytpoKpUf3iHahGlwkpz.jpg",
              "credit_id": "65e7851342f19f01878c55f7",
              "department": "Sound",
              "job": "Sound Designer"
          },
          {
              "adult": false,
              "gender": 2,
              "id": 3996,
              "known_for_department": "Sound",
              "name": "Tom Johnson",
              "original_name": "Tom Johnson",
              "popularity": 2.887,
              "profile_path": "/joF3OdCBQjzQ2keyQ9l7uhcZafo.jpg",
              "credit_id": "65e78520c15f890186157332",
              "department": "Sound",
              "job": "Sound Re-Recording Mixer"
          },
          {
              "adult": false,
              "gender": 2,
              "id": 1802871,
              "known_for_department": "Sound",
              "name": "Kris Bowers",
              "original_name": "Kris Bowers",
              "popularity": 2.662,
              "profile_path": "/qL0TnImRmCRIcoQy1d3GjTPKCLn.jpg",
              "credit_id": "65ec7b9e9a643501852e4360",
              "department": "Sound",
              "job": "Original Music Composer"
          },
          {
              "adult": false,
              "gender": 2,
              "id": 42267,
              "known_for_department": "Sound",
              "name": "Randy Thom",
              "original_name": "Randy Thom",
              "popularity": 2.425,
              "profile_path": "/oWv5U4r7NcIlQjs0IxMWE3dsx2l.jpg",
              "credit_id": "66b5f1d77ac78aea33c5ed4b",
              "department": "Sound",
              "job": "Sound Designer"
          },
          {
              "adult": false,
              "gender": 2,
              "id": 3504,
              "known_for_department": "Sound",
              "name": "David Farmer",
              "original_name": "David Farmer",
              "popularity": 3.815,
              "profile_path": "/oYNchEjc32GucUPvXAHMXajk3xJ.jpg",
              "credit_id": "66d3b690f199494501ae1a67",
              "department": "Sound",
              "job": "Sound Effects Editor"
          },
          {
              "adult": false,
              "gender": 1,
              "id": 1722927,
              "known_for_department": "Acting",
              "name": "Maren Morris",
              "original_name": "Maren Morris",
              "popularity": 0.872,
              "profile_path": "/zg3gnfGLWY9yL2yRuTurdmU98rG.jpg",
              "credit_id": "66ff1a0d7830c1301e7c9fee",
              "department": "Sound",
              "job": "Songs"
          },
          {
              "adult": false,
              "gender": 2,
              "id": 2717127,
              "known_for_department": "Art",
              "name": "Steven A. MacLeod",
              "original_name": "Steven A. MacLeod",
              "popularity": 1.167,
              "profile_path": null,
              "credit_id": "66ff46a67830c1301e7ca4a8",
              "department": "Art",
              "job": "Storyboard Artist"
          },
          {
              "adult": false,
              "gender": 0,
              "id": 3157179,
              "known_for_department": "Visual Effects",
              "name": "Genevieve Tsai",
              "original_name": "Genevieve Tsai",
              "popularity": 0.001,
              "profile_path": null,
              "credit_id": "66ff46b3e84eeb35a0f7fa1c",
              "department": "Art",
              "job": "Storyboard Artist"
          },
          {
              "adult": false,
              "gender": 0,
              "id": 1454722,
              "known_for_department": "Writing",
              "name": "Catherine Yuh Rader",
              "original_name": "Catherine Yuh Rader",
              "popularity": 0.259,
              "profile_path": null,
              "credit_id": "66ff46bde84eeb35a0f7fa1f",
              "department": "Art",
              "job": "Storyboard Artist"
          },
          {
              "adult": false,
              "gender": 0,
              "id": 1776007,
              "known_for_department": "Production",
              "name": "Benjamin Balistreri",
              "original_name": "Benjamin Balistreri",
              "popularity": 0.913,
              "profile_path": null,
              "credit_id": "66ff4742e84eeb35a0f7fa39",
              "department": "Art",
              "job": "Storyboard Artist"
          },
          {
              "adult": false,
              "gender": 0,
              "id": 2331836,
              "known_for_department": "Directing",
              "name": "Andrew Erekson",
              "original_name": "Andrew Erekson",
              "popularity": 0.046,
              "profile_path": null,
              "credit_id": "66ff4898fa3e69e0ef7cadd1",
              "department": "Art",
              "job": "Storyboard Artist"
          },
          {
              "adult": false,
              "gender": 2,
              "id": 2017050,
              "known_for_department": "Art",
              "name": "Taylor Meacham",
              "original_name": "Taylor Meacham",
              "popularity": 0.885,
              "profile_path": null,
              "credit_id": "66ff48cae480149146850484",
              "department": "Art",
              "job": "Storyboard Artist"
          },
          {
              "adult": false,
              "gender": 2,
              "id": 139686,
              "known_for_department": "Art",
              "name": "John Puglisi",
              "original_name": "John Puglisi",
              "popularity": 0.61,
              "profile_path": null,
              "credit_id": "66ff48d9e480149146850488",
              "department": "Art",
              "job": "Storyboard Artist"
          },
          {
              "adult": false,
              "gender": 0,
              "id": 4979736,
              "known_for_department": "Art",
              "name": "Sarah Gold Amburgey",
              "original_name": "Sarah Gold Amburgey",
              "popularity": 0.073,
              "profile_path": null,
              "credit_id": "66ff48fe67c6fb09fff7f1f1",
              "department": "Art",
              "job": "Additional Storyboarding"
          },
          {
              "adult": false,
              "gender": 2,
              "id": 1450351,
              "known_for_department": "Directing",
              "name": "Matt Flynn",
              "original_name": "Matt Flynn",
              "popularity": 0.569,
              "profile_path": null,
              "credit_id": "66ff491567c6fb09fff7f1ff",
              "department": "Art",
              "job": "Additional Storyboarding"
          },
          {
              "adult": false,
              "gender": 0,
              "id": 3643675,
              "known_for_department": "Camera",
              "name": "Daniel Tal",
              "original_name": "Daniel Tal",
              "popularity": 0.001,
              "profile_path": null,
              "credit_id": "66ff49431592ef1ba9850041",
              "department": "Art",
              "job": "Additional Storyboarding"
          },
          {
              "adult": false,
              "gender": 1,
              "id": 56660,
              "known_for_department": "Writing",
              "name": "Lorna Cook",
              "original_name": "Lorna Cook",
              "popularity": 1.823,
              "profile_path": "/fyIFFkzzgbKg5jYFPunIUfCxeLv.jpg",
              "credit_id": "66ff49561592ef1ba9850045",
              "department": "Art",
              "job": "Additional Storyboarding"
          },
          {
              "adult": false,
              "gender": 0,
              "id": 4979739,
              "known_for_department": "Art",
              "name": "Joanne Matte",
              "original_name": "Joanne Matte",
              "popularity": 0.083,
              "profile_path": null,
              "credit_id": "66ff49771592ef1ba985005c",
              "department": "Art",
              "job": "Additional Storyboarding"
          },
          {
              "adult": false,
              "gender": 2,
              "id": 1769896,
              "known_for_department": "Art",
              "name": "Nelson Yokota",
              "original_name": "Nelson Yokota",
              "popularity": 0.744,
              "profile_path": null,
              "credit_id": "66ff49809ebea19006f7f957",
              "department": "Art",
              "job": "Additional Storyboarding"
          },
          {
              "adult": false,
              "gender": 2,
              "id": 2872262,
              "known_for_department": "Art",
              "name": "Adam Rosette",
              "original_name": "Adam Rosette",
              "popularity": 0.498,
              "profile_path": null,
              "credit_id": "66ff498a925fdf925b7caf63",
              "department": "Art",
              "job": "Additional Storyboarding"
          },
          {
              "adult": false,
              "gender": 0,
              "id": 1272637,
              "known_for_department": "Crew",
              "name": "Chris Stover",
              "original_name": "Chris Stover",
              "popularity": 0.001,
              "profile_path": null,
              "credit_id": "67046176508dfa7ba3797c4d",
              "department": "Crew",
              "job": "Cinematography"
          },
          {
              "adult": false,
              "gender": 1,
              "id": 2012542,
              "known_for_department": "Production",
              "name": "Heather Lanza",
              "original_name": "Heather Lanza",
              "popularity": 0.4,
              "profile_path": null,
              "credit_id": "670461983d7b3c6c07797f5f",
              "department": "Production",
              "job": "Co-Producer"
          },
          {
              "adult": false,
              "gender": 2,
              "id": 2008370,
              "known_for_department": "Visual Effects",
              "name": "Ritchie Sacilioc",
              "original_name": "Ritchie Sacilioc",
              "popularity": 0.319,
              "profile_path": null,
              "credit_id": "670461c67cfea6f202740ccf",
              "department": "Art",
              "job": "Art Direction"
          },
          {
              "adult": false,
              "gender": 0,
              "id": 1445838,
              "known_for_department": "Sound",
              "name": "Leff Lefferts",
              "original_name": "Leff Lefferts",
              "popularity": 2.107,
              "profile_path": null,
              "credit_id": "670461ea7cfea6f202740cda",
              "department": "Sound",
              "job": "Sound Re-Recording Mixer"
          },
          {
              "adult": false,
              "gender": 2,
              "id": 138618,
              "known_for_department": "Sound",
              "name": "Gary Rizzo",
              "original_name": "Gary Rizzo",
              "popularity": 1.109,
              "profile_path": "/7FI3p2EeofGru26XD8bNpCjNLt1.jpg",
              "credit_id": "670461f77cfea6f202740cde",
              "department": "Sound",
              "job": "Sound Re-Recording Mixer"
          },
          {
              "adult": false,
              "gender": 0,
              "id": 3600202,
              "known_for_department": "Sound",
              "name": "Jeff Levy",
              "original_name": "Jeff Levy",
              "popularity": 0.379,
              "profile_path": null,
              "credit_id": "67046244cc904f12d913bcf5",
              "department": "Sound",
              "job": "ADR Mixer"
          },
          {
              "adult": false,
              "gender": 0,
              "id": 4996697,
              "known_for_department": "Visual Effects",
              "name": "Erik Tillmans",
              "original_name": "Erik Tillmans",
              "popularity": 0.0,
              "profile_path": null,
              "credit_id": "670b0f434111be4f02746fa7",
              "department": "Visual Effects",
              "job": "Effects Supervisor"
          }
      ]
  }
}